server:
  port: 8810

# 数据源配置
spring:
  application:
    name: service-data-system
  redis:
    #数据库索引
    database: 5
    host: 172.16.100.172
    port: 16379
    password: Pwksh_2019
    #连接超时时间
    timeout: 5000
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master: #采集专网库
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.100.101:3306/studio?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: admin
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: ${NACOS_ADDR:172.16.100.101:8848}
        # group: DEFAULT_GROUP
        group: ${NACOS_GROUP:datax}

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.datax.service.system.api.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# spring security 配置
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8612/auth/oauth/token
      user-authorization-uri: http://localhost:8612/auth/oauth/authorize
      client-id: AllData
      client-secret: 123456
      scope: all
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:8612/auth/oauth/check_token

# Swagger界面内容配置
swagger:
  enable: true
  title: API接口文档
  description: Api Documentation
  version: 1.0.0
  basePackage: cn.datax.service.system.controller
  termsOfServiceUrl: https://github.com/alldatacenter/alldata
  contact:
    name: AllDataDC
    url: https://github.com/alldatacenter/alldata
    email: m13602574132@163.com
